modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Hydroline/hydroline-HydroNyaSama/issues"
showAsResourcePack=false

[[mods]]
modId="hydronyasama"
version="${version}"
displayName="HydroNyaSama"
updateJSONURL=""
displayURL="https://github.com/Hydroline/hydroline-HydroNyaSama"
credits=""
authors="Hydroline"
description='''
Bridge mod entrypoint for HydroNyaSama on Forge.
'''

[[dependencies.hydronyasama]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.hydronyasama]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
